// import EmblaCarousel from "./(dashboard)/carousel/page"
import Home from "./(dashboard)/home/page"

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
  }
  
  export default function RootLayout({ children }) {

      if (children === undefined) {
        children = <Home />;
      };

    console.log('children', children)

    return (
        <html lang="en">
            <body className="root-layout-test">{children}</body>
        </html>
    )
  }
  